# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-03 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
