# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180603_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='face',
            field=models.ImageField(default='icon/default.jpeg', max_length=128, upload_to='icon/'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('1', '男'), ('2', '女'), ('3', '保密')], default='1', max_length=32),
        ),
    ]
