# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180604_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='face',
            new_name='images',
        ),
    ]
